version: '3'
services:
  db:
    image: postgres
    container_name: spring-mvc-legacy-db
    restart: always
    volumes:
      - spring-mvc-legacy:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 'password'
      TZ: 'Asia/Seoul'

volumes:
  spring-mvc-legacy:
